---
- hosts: all
  become: true

  tasks:
    - name: Copy files
      copy:
        src: /home/ray/tms-git/tms-git/examples/yandex/copy/
        dest: /home/ubuntu

    - name: Add user to group
      user:
        name: ubuntu
        groups: docker
        append: true

    - name: Build a Docker image
      command: docker build -t jenkins:jcasc .

    - name: Run a Docker container
      command: docker run --name jenkins -p 8080:8080 -d jenkins:jcasc
